### ISSUE TITLE
are these musical keys named/labelled correctly?

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/apiapi#8]
@mcleanGit If there is anything below that you would change, could you please make the suggestion? It's been a while since I thought about music theory!

```javascript
var keys = {
    major: ['C', 'C#/Bb', 'D', 'D#/Eb', 'E', 'F', 'F#Gb', 'G', 'G#/Ab', 'A', 'A#/Bb', 'B'],
    minor: ['C', 'C#/Bb', 'D', 'D#/Eb', 'E', 'F', 'F#Gb', 'G', 'G#/Ab', 'A', 'A#/Bb', 'B']
}
```

**Comment by mcleanGit** [comment]
Hi, Michael.
Will revise a few details by tomorrow am.


Don McLean
Professor of Musicology and
Music Theory
Faculty of Music
University of Toronto
Edward Johnson Building
80 Queen's Park Cr.
Toronto, ON, Canada
M5S 2C5
T: 647-921-3761
E: ***@***.***
W: www.music.utoronto.ca

On Feb 3, 2022, at 22:18, Michael Palumbo ***@***.***> wrote:

﻿

Assigned #8<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelpalumbo%2Fapiapi%2Fissues%2F8&data=04%7C01%7Cmclean%40utoronto.ca%7C711507a7d51148c6ee3308d9e78d0894%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795415180919363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k%2Bl2YL%2B3ezS%2BHdG89009P1JjtWTfm%2BfzldNZaJAZrZY%3D&reserved=0> to @mcleanGit<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmcleanGit&data=04%7C01%7Cmclean%40utoronto.ca%7C711507a7d51148c6ee3308d9e78d0894%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795415181075584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p6DE8QpBKuE%2FWj283eCLZiJK6AHCdFrM%2FauLsMDOrzQ%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelpalumbo%2Fapiapi%2Fissues%2F8%23event-6006945157&data=04%7C01%7Cmclean%40utoronto.ca%7C711507a7d51148c6ee3308d9e78d0894%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795415181075584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q9P8Fl9ligHY6f3LNd5kAE3C6Z20Mf1bfNP%2BNYy2l0g%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWTWXNOLMQXZ23JQNIF5CWLUZNAQZANCNFSM5NQVKF3A&data=04%7C01%7Cmclean%40utoronto.ca%7C711507a7d51148c6ee3308d9e78d0894%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795415181075584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZQRS8Sp6LcXAGjwnVs7e6NAYj8fZp8V9I7cO0wA75Qw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmclean%40utoronto.ca%7C711507a7d51148c6ee3308d9e78d0894%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795415181075584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rZKcc7fSx9jcMIIUEOm6pglHtuED9TkkLp1ue3IqU4g%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmclean%40utoronto.ca%7C711507a7d51148c6ee3308d9e78d0894%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795415181075584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G6%2BDU5xfI2qEonER4UYbdebchK9pSnVkAJvvYNZRqCo%3D&reserved=0>.

**Comment by michaelpalumbo** [comment]
> Hi, Michael. Will revise a few details by tomorrow am.

Awesome, thanks Don!

**Comment by mcleanGit** [comment]
// here is the revised list //
var keys = {
    major: ['C', 'C#/Db', 'D', 'Eb', 'E', 'F', 'F#Gb', 'G', 'Ab', 'A', 'Bb', 'B/Cb'],
    minor: ['C', 'C#', 'D', 'D#/Eb', 'E', 'F', 'F#', 'G', 'G#/Ab', 'A', 'A#/Bb', 'B']
// this is 'complete'-- from 0 sharps and flats (C major/ A minor) to 7 sharps (C# major/ A# minor) or 7 flats (Cb major/ Ab minor), this number of sharps and flats very rare, particularly in popular song repertoire, but OK for our completeness //
// could consider using common convention of lower-case for minor keys and chords, thus: //
 minor: ['c', 'c#', 'd', 'd#/eb', 'e', 'f', 'f#', 'g', g#/ab', 'a', 'a#/bb', 'b']
// although guitar tablature uses Em rather than em, so maybe stick with the upper case //
// we should use actual # and b symbols rather than alpha characters //
}

**Comment by mcleanGit** [comment]
This should close this issue, but a couple of decisions to be made.

**Comment by mcleanGit** [comment]
Posted to Issue #8 and closed.
The revision and some final comments here.
Oops: forgot the slash F#/Gb.  Sorry.
Should be able to finalize this now.
// here is the revised list //
var keys = {
major: ['C', 'C#/Db', 'D', 'Eb', 'E', 'F', 'F#Gb', 'G', 'Ab', 'A', 'Bb', 'B/Cb'],
minor: ['C', 'C#', 'D', 'D#/Eb', 'E', 'F', 'F#', 'G', 'G#/Ab', 'A', 'A#/Bb', 'B']
// this is 'complete'-- from 0 sharps and flats (C major/ A minor) to 7 sharps (C# major/ A# minor) or 7 flats (Cb major/ Ab minor), this number of sharps and flats very rare, particularly in popular song repertoire, but OK for our completeness //
// could consider using common convention of lower-case for minor keys and chords, thus: //
minor: ['c', 'c#', 'd', 'd#/eb', 'e', 'f', 'f#', 'g', g#/ab', 'a', 'a#/bb', 'b']
// although guitar tablature uses Em rather than em, so maybe stick with the upper case //
// we should use actual # and b symbols rather than alpha characters //
}


From: Michael Palumbo ***@***.***>
Reply-To: michaelpalumbo/apiapi ***@***.***>
Date: Friday, February 4, 2022 at 10:04 AM
To: michaelpalumbo/apiapi ***@***.***>
Cc: Don McLean ***@***.***>, Mention ***@***.***>
Subject: Re: [michaelpalumbo/apiapi] are these musical keys named/labelled correctly? (Issue #8)


Hi, Michael. Will revise a few details by tomorrow am.

Awesome, thanks Don!

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelpalumbo%2Fapiapi%2Fissues%2F8%23issuecomment-1030070310&data=04%7C01%7Cmclean%40utoronto.ca%7Ceb3b7bbe1f504d5554a408d9e7efb570%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795838994425873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=94vgFJP7EUVv39sC0WhNZnFI8SruO4wRORwC4UcRjNM%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWTWXNMWQUZRQ5OW6N2CXHTUZPTJTANCNFSM5NQVKF3A&data=04%7C01%7Cmclean%40utoronto.ca%7Ceb3b7bbe1f504d5554a408d9e7efb570%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795838994425873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FYwNvxcdPBK7Gs4Fb9isCU9Qk842RO72wCp%2BnTcECW4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmclean%40utoronto.ca%7Ceb3b7bbe1f504d5554a408d9e7efb570%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795838994425873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V1n7ZSpFjZjgOgcQeqRd8W9Xx3Ni9iH6V5Wx5A5ik2k%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmclean%40utoronto.ca%7Ceb3b7bbe1f504d5554a408d9e7efb570%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795838994425873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DG5q0ht8TYdMpczvC6rZhVDsEeEGCHdvP3O51im4zgo%3D&reserved=0>.

**Comment by michaelpalumbo** [comment]
Hey @mcleanGit i'm just reopening this issue until I have a chance to read it over and implement your suggestions, thanks!

**Comment by mcleanGit** [comment]
Good. Should be straightforward.

Don McLean
Professor of Musicology and
Music Theory
Faculty of Music
University of Toronto
Edward Johnson Building
80 Queen's Park Cr.
Toronto, ON, Canada
M5S 2C5
T: 647-921-3761
E: ***@***.***
W: www.music.utoronto.ca

On Feb 4, 2022, at 14:30, Michael Palumbo ***@***.***> wrote:

﻿

Reopened #8<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelpalumbo%2Fapiapi%2Fissues%2F8&data=04%7C01%7Cmclean%40utoronto.ca%7C2436aae41bf048c0345d08d9e814d950%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795998505464929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6X1eWu4%2F4HB62dWawoEUWoG%2Bg4FEcRPMKs4Gd6ocZ%2FU%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelpalumbo%2Fapiapi%2Fissues%2F8%23event-6011596493&data=04%7C01%7Cmclean%40utoronto.ca%7C2436aae41bf048c0345d08d9e814d950%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795998505621178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PTsCW43okm%2BjId7Im4iXsxrUIjuQKy9MqSZqCa78EAA%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWTWXNKCWB2ZUQZVIYKE24LUZQSORANCNFSM5NQVKF3A&data=04%7C01%7Cmclean%40utoronto.ca%7C2436aae41bf048c0345d08d9e814d950%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795998505621178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1cvBUPjSAwvFE66mJbX1nzqnb2C2Vo9GKFJNciNXkvA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmclean%40utoronto.ca%7C2436aae41bf048c0345d08d9e814d950%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795998505621178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mL%2F342AzzezDef6yleUP7V1J5fbgeTqfD2qIH8ksyy0%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmclean%40utoronto.ca%7C2436aae41bf048c0345d08d9e814d950%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637795998505621178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=djPVfh%2BA1bcJjkFFD5LoXVlJtQwLvXBW9uqKrCUw3wU%3D&reserved=0>.

**Comment by michaelpalumbo** [comment]
Thanks Don. I've incorporated these changes in a recent commit.
